controller_manager:
  ros__parameters:
    update_rate: 50 #Hz

    # Publish all joint states -----------------------------------
    joint_state_controller:
      type: joint_state_controller/JointStateController

    # Velocity Controllers ---------------------------------------
    left_rear_wheel_velocity_controller:
      type: effort_controllers/JointVelocityController

    right_rear_wheel_velocity_controller:
      type: effort_controllers/JointVelocityController

    left_front_wheel_velocity_controller:
      type: effort_controllers/JointVelocityController

    right_front_wheel_velocity_controller:
      type: effort_controllers/JointVelocityController

    # Position Controllers ---------------------------------------
    left_steering_hinge_position_controller:
      type: effort_controllers/JointPositionController
    right_steering_hinge_position_controller:
      type: effort_controllers/JointPositionController


left_rear_wheel_velocity_controller:
  ros__parameters:
    joint: left_rear_wheel_joint
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
right_rear_wheel_velocity_controller:
  ros__parameters:
    joint: right_rear_wheel_joint
    pid: {p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0}
left_front_wheel_velocity_controller:
  ros__parameters:
    joint: left_front_wheel_joint
    pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}
right_front_wheel_velocity_controller:
  ros__parameters:
    joint: right_front_wheel_joint
    pid: {p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0}


# Position Controllers ---------------------------------------
left_steering_hinge_position_controller:
  ros__parameters:
    joint: left_steering_hinge_joint
    pid: {p: 1.0, i: 0.0, d: 0.5}
right_steering_hinge_position_controller:
  ros__parameters:
    joint: right_steering_hinge_joint
    pid: {p: 1.0, i: 0.0, d: 0.5}

