controller_manager:
  ros__parameters:
    update_rate: 100 #Hz

    # Publish all joint states -----------------------------------
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # Velocity Controllers ---------------------------------------
    left_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_rear_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    left_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    right_front_wheel_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    # Position Controllers ---------------------------------------
    left_steering_hinge_position_controller:
      type: position_controllers/JointGroupPositionController
    right_steering_hinge_position_controller:
      type: position_controllers/JointGroupPositionController


left_rear_wheel_velocity_controller:
  ros__parameters:
    joints: 
      - left_rear_wheel_joint
    state_interfaces: 
      - velocity
      - position
      - effort
    command_interfaces: 
      - velocity

right_rear_wheel_velocity_controller:
  ros__parameters:
    joints: 
      - right_rear_wheel_joint
    state_interfaces: 
      - velocity
      - position
      - effort
    command_interfaces: 
      - velocity

left_front_wheel_velocity_controller:
  ros__parameters:
    joints: 
      - left_front_wheel_joint
    state_interfaces: 
      - velocity
      - position
      - effort
    command_interfaces: 
      - velocity

right_front_wheel_velocity_controller:
  ros__parameters:
    joints: 
      - right_front_wheel_joint
    state_interfaces: 
      - velocity
      - position
      - effort
    command_interfaces: 
      - velocity


# Position Controllers ---------------------------------------
left_steering_hinge_position_controller:
  ros__parameters:
    joints: 
      - left_steering_hinge_joint
    state_interfaces: 
      - velocity
      - position
    command_interfaces: 
      - position

right_steering_hinge_position_controller:
  ros__parameters:
    joints: 
      - right_steering_hinge_joint
    state_interfaces: 
      - velocity
      - position
    command_interfaces: 
      - position