D435:
  ros__parameters:
    camera_name: D435
    accel_fps: -1.0
    accel_frame_id: camera_accel_frame
    accel_info_qos: DEFAULT
    accel_optical_frame_id: camera_accel_optical_frame
    accel_qos: HID_DEFAULT
    align_depth: false
    aligned_depth_to_color_frame_id: camera_aligned_depth_to_color_frame
    allow_no_texture_points: false
    angular_velocity_cov: 0.01
    base_frame_id: camera_link
    #base_frame_id: d435_throwaway_frame
    clip_distance: -2.0
    color_extrinsics_qos: EXTRINSICS_DEFAULT
    color_fps: -1.0
    color_frame_id: camera_color_frame
    color_height: -1
    color_info_qos: DEFAULT
    color_optical_frame_id: camera_color_optical_frame
    color_qos: SYSTEM_DEFAULT
    color_width: -1
    confidence_fps: -1.0
    confidence_frame_id: camera_confidence_frame
    confidence_height: -1
    confidence_info_qos: DEFAULT
    confidence_optical_frame_id: camera_confidence_optical_frame
    confidence_qos: SYSTEM_DEFAULT
    confidence_width: -1
    depth_fps: -1.0
    depth_frame_id: camera_depth_frame
    depth_height: -1
    depth_info_qos: DEFAULT
    depth_optical_frame_id: camera_depth_optical_frame
    depth_qos: SYSTEM_DEFAULT
    depth_width: -1
    device_type: d435
    enable_accel: false
    enable_color: true
    enable_confidence: true
    enable_depth: true
    enable_fisheye: true
    enable_fisheye1: true
    enable_fisheye2: true
    enable_gyro: false
    enable_infra: true
    enable_infra1: true
    enable_infra2: true
    enable_pointcloud: false
    enable_pose: true
    enable_sync: false
    filters: ''
    fisheye1_frame_id: camera_fisheye1_frame
    fisheye1_optical_frame_id: camera_fisheye1_optical_frame
    fisheye2_frame_id: camera_fisheye2_frame
    fisheye2_optical_frame_id: camera_fisheye2_optical_frame
    fisheye_extrinsics_qos: EXTRINSICS_DEFAULT
    fisheye_fps: -1.0
    fisheye_frame_id: camera_fisheye_frame
    fisheye_height: -1
    fisheye_info_qos: DEFAULT
    fisheye_optical_frame_id: camera_fisheye_optical_frame
    fisheye_qos: SYSTEM_DEFAULT
    fisheye_width: -1
    gyro_fps: -1.0
    gyro_frame_id: camera_gyro_frame
    gyro_info_qos: DEFAULT
    gyro_optical_frame_id: camera_gyro_optical_frame
    gyro_qos: HID_DEFAULT
    hold_back_imu_for_frames: false
    infra1_extrinsics_qos: EXTRINSICS_DEFAULT
    infra1_frame_id: camera_infra1_frame
    infra1_optical_frame_id: camera_infra1_optical_frame
    infra2_extrinsics_qos: EXTRINSICS_DEFAULT
    infra2_frame_id: camera_infra2_frame
    infra2_optical_frame_id: camera_infra2_optical_frame
    infra_fps: -1.0
    infra_frame_id: camera_infra_frame
    infra_height: -1
    infra_info_qos: DEFAULT
    infra_optical_frame_id: camera_infra_optical_frame
    infra_qos: SYSTEM_DEFAULT
    infra_rgb: false
    infra_width: -1
    initial_reset: true
    json_file_path: ''
    linear_accel_cov: 0.01
    odom_frame_id: odom_frame
    ordered_pc: false
    pointcloud_texture_index: 0
    pointcloud_texture_stream: RS2_STREAM_COLOR
    pose_fps: 0.0
    pose_frame_id: camera_pose_frame
    pose_info_qos: DEFAULT
    pose_optical_frame_id: camera_pose_optical_frame
    pose_qos: HID_DEFAULT
    publish_odom_tf: true
    publish_tf: true
    rgb_camera:
      auto_exposure_priority: false
      auto_exposure_roi:
        bottom: 479
        left: 0
        right: 639
        top: 0
      backlight_compensation: false
      brightness: 0
      contrast: 50
      enable_auto_exposure: true
      enable_auto_white_balance: true
      exposure: 166
      frames_queue_size: 16
      gain: 64
      gamma: 300
      global_time_enabled: true
      hue: 0
      power_line_frequency: 3
      saturation: 64
      sharpness: 50
      white_balance: 4600.0
    rosbag_filename: ''
    serial_no: ''
    stereo_module:
      auto_exposure_limit: 0
      auto_exposure_roi:
        bottom: 479
        left: 0
        right: 639
        top: 0
      auto_gain_limit: 0
      emitter_always_on: false
      emitter_enabled: 1
      emitter_on_off: false
      enable_auto_exposure: true
      error_polling_enabled: true
      exposure: 8500
      frames_queue_size: 16
      gain: 16
      global_time_enabled: true
      hdr_enabled: false
      inter_cam_sync_mode: 0
      laser_power: 150.0
      output_trigger_enabled: false
      sequence_id: 0
      sequence_name: 0
      sequence_size: 2
      visual_preset: 0
    tf_publish_rate: 0.0
    unite_imu_method: ''
    usb_port_id: ''
    use_sim_time: false
